# Generated by Django 3.1.5 on 2021-01-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nazwa towaru')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Zdjecie')),
                ('description', models.TextField(verbose_name='Opis towaru')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Cena')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Cale')),
                ('display_type', models.CharField(max_length=255, verbose_name='Typ displeja')),
                ('resolution', models.CharField(max_length=255, verbose_name='Rozdzielczosc ekranu')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Objętosc baterii')),
                ('ram', models.CharField(max_length=255, verbose_name='RAM')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume_max', models.CharField(max_length=255, verbose_name='Objętość pamieci')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Glowna kamera')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Selfi camera')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Kategoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nazwa towaru')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Zdjecie')),
                ('description', models.TextField(verbose_name='Opis towaru')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Cena')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Cale')),
                ('display_type', models.CharField(max_length=255, verbose_name='Typ displeja')),
                ('processor_freg', models.CharField(max_length=255, verbose_name='Czastotnosc procesora')),
                ('ram', models.CharField(max_length=255, verbose_name='RAM')),
                ('video', models.CharField(max_length=255, verbose_name='Karta graficzna')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Czas pracy baterii')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Kategoria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
