# Generated by Django 3.1.5 on 2021-02-04 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210204_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Imie')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nazwisko')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Adres')),
                ('status', models.CharField(default='new', max_length=100, verbose_name=(('new', 'Nowe zamowienie'), ('in_progress', 'Zamowienie w toku'), ('is_ready', 'Zamowienie gotowe'), ('completed', 'Zamowienie wykonane')))),
                ('buying_type', models.CharField(choices=[('self', 'Odbior osobisty'), ('delivery', 'Z dostawa')], default='self', max_length=100, verbose_name='Typ zamowienia')),
                ('comment', models.TextField(blank='True', null=True, verbose_name='Komentarz do zamowienia')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Data stworzenia zamowienia')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data otrymania zamowienia')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='mainapp.customer', verbose_name='Klient')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='mainapp.Order', verbose_name='zamowienia klienta'),
        ),
    ]
